# Generated by Django 5.0.4 on 2024-04-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('razao_social', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco_logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_cep', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
