# Generated by Django 5.0.4 on 2024-04-23 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField()),
                ('endereco_logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone_residencial', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=15, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('ativo', models.BooleanField(default=True)),
                ('visitante', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Pr', 'Pastor'), ('Pb', 'Presbítero'), ('Dc', 'Diácono')], max_length=2)),
                ('inicio_mandato', models.DateField()),
                ('fim_mandato', models.DateField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.pessoa')),
            ],
            options={
                'verbose_name_plural': 'Oficiais',
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('ausente', models.BooleanField(default=False)),
                ('baixa_frequencia', models.BooleanField(default=False)),
                ('necessidades_especiais', models.BooleanField(default=False)),
                ('profissao_fe', models.BooleanField(default=False)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.igreja')),
                ('membro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membro', to='members.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(choices=[('A', 'Admissão'), ('D', 'Desligamento'), ('P', 'Profissão de Fé')], max_length=1)),
                ('tipo_admissao', models.CharField(blank=True, choices=[('B', 'Batismo'), ('T', 'Transferência'), ('J', 'Jurisdição')], max_length=1, null=True)),
                ('tipo_desligamento', models.CharField(blank=True, choices=[('E', 'Exclusão'), ('T', 'Transferência'), ('F', 'Falecimento')], max_length=1, null=True)),
                ('data', models.DateField()),
                ('livro', models.CharField(max_length=10)),
                ('ata', models.CharField(max_length=10)),
                ('folha', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.CharField(max_length=10)),
                ('ano', models.CharField(max_length=10)),
                ('observacao', models.TextField()),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_atas', to='church.igreja')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ata', to='members.pessoa')),
            ],
        ),
    ]
