# Generated by Django 5.0.2 on 2024-02-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco_logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone_residencial', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=15, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembroRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=10)),
                ('ata', models.CharField(max_length=10)),
                ('folha', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.CharField(max_length=10)),
                ('ano', models.CharField(max_length=10)),
                ('data_recepcao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ausente', models.BooleanField(default=False)),
                ('baixa_frequencia', models.BooleanField(default=False)),
                ('necessidades_especiais', models.BooleanField(default=False)),
                ('profissao_fe', models.BooleanField(default=False)),
                ('membro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.membro')),
            ],
        ),
    ]
