# Generated by Django 5.0.2 on 2024-02-11 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Pr', 'Pastor'), ('Pb', 'Presbítero'), ('Dc', 'Diácono')], max_length=2)),
                ('inicio_mandato', models.DateField()),
                ('fim_mandato', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('membro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.pessoa')),
            ],
            options={
                'verbose_name_plural': 'Oficiais',
            },
        ),
    ]
