# Generated by Django 5.0.2 on 2024-02-11 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_oficial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficial',
            name='fim_mandato',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='oficial',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.pessoa'),
        ),
    ]
